- name: Ensure old versions of Docker are not installed.
  package:
    name:
    - docker
    - docker-engine
    state: absent

- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true
    autoremove: true
    cache_valid_time: 86400 

- name: Install list of packages
  package:
    name:    
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    state: latest 
    update_cache: yes
    
- name: APT - Add Docker GPG key
  apt_key: 
    keyserver: keyserver.ubuntu.com 
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    
- name: Add Docker goup
  user:
    name: "{{ theuser }}"
    append: yes
    groups: docker

# - name: Install Portainer
#   docker_container:
#     name: MyPortainer
#     image: "portainer/portainer"
#     ports: 
#       - "9000:9000"

# - name: Stop Docker daemon
#   systemd:
#     name: docker
#     state: stopped

# - name: Check if /etc/docker/daemon.json exists
#   stat:
#     path: /etc/docker/daemon.json
#   register: cfgfile  

# - name: Create /etc/docker/daemon.json
#   copy:
#     dest:  /etc/docker/daemon.json
#     content: |
#       {
#         "data-root": "{{ docker_persistent_dir }}"
#       }
#   when: not cfgfile.stat.exists
#   notify:
#     - Restart Docker

# - name: Change Docker data root
#   replace:
#     path: /etc/docker/daemon.json
#     regexp: '/var/lib/docker'
#     replace: "{{ docker_persistent_dir }}"
#   when: cfgfile.stat.exists
#   notify:
#     - Restart Docker
    
    
